/**
 * Mock vehicle database for FIPE simulation
 * Since there's no free/official API for license plate lookup in Brazil,
 * this mock provides realistic vehicle data for development and academic purposes.
 *
 * 25 vehicles with different plates, models, brands, and types.
 */

import { FipeVehicleData } from './fipe.types';

export interface MockVehicleEntry {
  placa: string;
  data: FipeVehicleData;
}

/**
 * Mock database of vehicles indexed by normalized plate (no hyphens, uppercase)
 */
export const MOCK_VEHICLES: Record<string, FipeVehicleData> = {
  // --- Carros ---
  'ABC1234': {
    brand: 'Fiat',
    model: 'Uno 1.0 Fire',
    year: 2010,
    fuel: 'Gasolina',
    fipeValue: 18500,
    color: 'Prata',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'XYZ5678': {
    brand: 'Volkswagen',
    model: 'Gol 1.6 Power',
    year: 2015,
    fuel: 'Gasolina',
    fipeValue: 32000,
    color: 'Branco',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'DEF9012': {
    brand: 'Chevrolet',
    model: 'Onix 1.0 Turbo',
    year: 2022,
    fuel: 'Gasolina',
    fipeValue: 72000,
    color: 'Preto',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'GHI3456': {
    brand: 'Hyundai',
    model: 'HB20 1.0 Comfort',
    year: 2021,
    fuel: 'Gasolina',
    fipeValue: 65000,
    color: 'Vermelho',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'JKL7890': {
    brand: 'Toyota',
    model: 'Corolla 2.0 XEi',
    year: 2023,
    fuel: 'Gasolina',
    fipeValue: 135000,
    color: 'Cinza',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'MNO1122': {
    brand: 'Honda',
    model: 'Civic 2.0 EXL',
    year: 2022,
    fuel: 'Gasolina',
    fipeValue: 128000,
    color: 'Azul',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'PQR3344': {
    brand: 'Ford',
    model: 'Ka 1.5 SE',
    year: 2019,
    fuel: 'Gasolina',
    fipeValue: 42000,
    color: 'Branco',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'STU5566': {
    brand: 'Renault',
    model: 'Kwid 1.0 Zen',
    year: 2023,
    fuel: 'Gasolina',
    fipeValue: 58000,
    color: 'Laranja',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'VWX7788': {
    brand: 'Jeep',
    model: 'Renegade 1.8 Sport',
    year: 2021,
    fuel: 'Gasolina',
    fipeValue: 95000,
    color: 'Verde',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'BRA2E19': {
    brand: 'Fiat',
    model: 'Argo 1.3 Drive',
    year: 2024,
    fuel: 'Gasolina',
    fipeValue: 78000,
    color: 'Prata',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'RIO4F56': {
    brand: 'Volkswagen',
    model: 'T-Cross 1.0 TSI',
    year: 2023,
    fuel: 'Gasolina',
    fipeValue: 115000,
    color: 'Branco',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'SAO7G89': {
    brand: 'Chevrolet',
    model: 'Tracker 1.0 Turbo',
    year: 2024,
    fuel: 'Gasolina',
    fipeValue: 125000,
    color: 'Preto',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'MIN1H23': {
    brand: 'Nissan',
    model: 'Kicks 1.6 SL',
    year: 2022,
    fuel: 'Gasolina',
    fipeValue: 98000,
    color: 'Cinza',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'CUR4J56': {
    brand: 'Peugeot',
    model: '208 1.6 Griffe',
    year: 2021,
    fuel: 'Gasolina',
    fipeValue: 75000,
    color: 'Azul',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'POA7K89': {
    brand: 'Citroën',
    model: 'C3 1.6 Live',
    year: 2020,
    fuel: 'Gasolina',
    fipeValue: 55000,
    color: 'Vermelho',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'BEL2L34': {
    brand: 'Caoa Chery',
    model: 'Tiggo 5X 1.5 Turbo',
    year: 2023,
    fuel: 'Gasolina',
    fipeValue: 105000,
    color: 'Branco',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'REC5M67': {
    brand: 'Toyota',
    model: 'Hilux 2.8 SRX',
    year: 2024,
    fuel: 'Diesel',
    fipeValue: 285000,
    color: 'Prata',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  'FLO8N90': {
    brand: 'Mitsubishi',
    model: 'L200 Triton 2.4',
    year: 2022,
    fuel: 'Diesel',
    fipeValue: 210000,
    color: 'Preto',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
  // --- Motos ---
  'MOT1A23': {
    brand: 'Honda',
    model: 'CG 160 Fan',
    year: 2023,
    fuel: 'Gasolina',
    fipeValue: 14500,
    color: 'Vermelho',
    vehicleType: 'Moto',
    retrievedAt: new Date().toISOString(),
  },
  'MOT4B56': {
    brand: 'Yamaha',
    model: 'Fazer 250 ABS',
    year: 2024,
    fuel: 'Gasolina',
    fipeValue: 22000,
    color: 'Azul',
    vehicleType: 'Moto',
    retrievedAt: new Date().toISOString(),
  },
  'MOT7C89': {
    brand: 'Honda',
    model: 'CB 500F',
    year: 2022,
    fuel: 'Gasolina',
    fipeValue: 35000,
    color: 'Preto',
    vehicleType: 'Moto',
    retrievedAt: new Date().toISOString(),
  },
  'MOT2D34': {
    brand: 'Kawasaki',
    model: 'Ninja 400',
    year: 2023,
    fuel: 'Gasolina',
    fipeValue: 38000,
    color: 'Verde',
    vehicleType: 'Moto',
    retrievedAt: new Date().toISOString(),
  },
  'MOT5E67': {
    brand: 'BMW',
    model: 'G 310 GS',
    year: 2024,
    fuel: 'Gasolina',
    fipeValue: 42000,
    color: 'Branco',
    vehicleType: 'Moto',
    retrievedAt: new Date().toISOString(),
  },
  // --- Caminhões ---
  'CAM1F23': {
    brand: 'Mercedes-Benz',
    model: 'Accelo 1016',
    year: 2021,
    fuel: 'Diesel',
    fipeValue: 195000,
    color: 'Branco',
    vehicleType: 'Caminhão',
    retrievedAt: new Date().toISOString(),
  },
  'CAM4G56': {
    brand: 'Volkswagen',
    model: 'Delivery 11.180',
    year: 2022,
    fuel: 'Diesel',
    fipeValue: 220000,
    color: 'Branco',
    vehicleType: 'Caminhão',
    retrievedAt: new Date().toISOString(),
  },
  // --- Placa da imagem ---
  'WEZ5C09': {
    brand: 'Chevrolet',
    model: 'Prisma 1.4 LTZ',
    year: 2018,
    fuel: 'Gasolina',
    fipeValue: 48000,
    color: 'Prata',
    vehicleType: 'Carro',
    retrievedAt: new Date().toISOString(),
  },
};
